### ISSUE TITLE
Use tags to generate a index page with hierachies

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-documentation#36]
extend jekyll to not only use the first tag as header for grouping pages on the index page but also use tags 2 +3 for that.

**Comment by metas-ts** [comment]
@metasnw gave me the specs on [google drive](https://docs.google.com/spreadsheets/d/1Ldx9RT76-69VGwlM8a55UmKXUdwtezkac5ek8bbhy1M/edit?usp=sharing)

**Comment by metas-ts** [comment]
Hi @metasnw ,
I implemented userstory 1. you can see it at http://docs.metasfresh.org/pages/howto/tag_hierarchical_index_de (currently not linked from the main index page).

It took longer because i tend to expect to much from liquid and then need to restart in more simple ways...think I'm *slowly* building up a feeling for the language.
Also, I do a lot of syntax errors, and some of them are hard to see&fix (for me at least).

As an outlook, the other Us should take less time, but i think for this week my time-budget is exhaustet. Also i'm not sure i fully understood u3 yet. Let's talk..
